import os
import sys
import time
import glob
import subprocess
import json
import platform
import socket
import tempfile
import yaml
from datetime import datetime


TASKS_DIR = "IsaacLab_Tasks"
LAST_COMMAND_FILE = ".launcher_last_command.json"
CONFIG_PATH = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Configs", "config.yaml"))

# Global Environment Detection
IS_DOCKER = os.path.exists("/.dockerenv")
IS_ROBOT = platform.machine().lower() in ["aarch64", "arm64"]

def discovery_server_address():
    """The configured FastDDS discovery server address ("host:port")."""
    server = "10.42.0.1:11811"
    try:
        with open(CONFIG_PATH, "r") as f:
            net = (yaml.safe_load(f) or {}).get("network", {}) or {}
        server = str(net.get("discovery_server", server))
    except Exception:
        pass
    return server


def _discovery_server_running():
    """True if a fast-discovery-server process is running on THIS machine."""
    try:
        return subprocess.run(["pgrep", "-f", "fast-discovery-server"],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                              timeout=5).returncode == 0
    except Exception:
        return False


def resolve_discovery_server():
    """Return (server, local_ip) for the wireless path, or (None, None) for cable.

    The robot's WiFi AP drops multicast, so DDS discovery never completes over
    wireless even though ping is fine — `ros2 topic list` just comes back empty.
    A discovery server on the robot replaces multicast with unicast client/server.
    On cable multicast works, so this stays off there.

    config.yaml -> network.discovery_mode: auto (default) | on | off
    """
    server, mode = discovery_server_address(), "auto"
    try:
        with open(CONFIG_PATH, "r") as f:
            net = (yaml.safe_load(f) or {}).get("network", {}) or {}
        mode = str(net.get("discovery_mode", mode)).lower()
    except Exception:
        pass

    if mode == "off":
        return None, None

    # auto: only when this machine sits on the server's subnet, i.e. it joined the
    # robot's hotspot rather than the wired network. connect() on a UDP socket
    # sends nothing — it just resolves which local address the route would use.
    host, _, port = server.partition(":")
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(0.2)
        sock.connect((host, int(port or 11811)))
        local_ip = sock.getsockname()[0]
        sock.close()
    except Exception:
        return (server, None) if mode == "on" else (None, None)

    if mode == "on":
        return server, local_ip

    if local_ip == host:
        # This machine hosts the discovery server - the robot, which is also the
        # AP and therefore ALWAYS holds this address. Subnet checks cannot tell
        # WiFi from cable here, so ask the process table instead: the server
        # would be running locally. Running it is the operator's way of saying
        # "we are on wireless", which is exactly the intent we want to follow.
        return (server, local_ip) if _discovery_server_running() else (None, None)

    same_subnet = local_ip.rsplit(".", 1)[0] == host.rsplit(".", 1)[0]
    return (server, local_ip) if same_subnet else (None, None)


def write_fastdds_profile(local_ip):
    """Pin FastDDS to one interface; returns the profile path, or None.

    Both machines are multi-homed (several wired subnets plus the robot's WiFi
    AP). A participant otherwise advertises every address it owns, the peer picks
    one that does not route, and data silently never arrives even though
    discovery succeeded and `ros2 topic info` shows the endpoints. Generated at
    runtime from the address that actually reaches the robot, so there is nothing
    machine-specific stored in the repo.
    """
    if not local_ip:
        return None
    path = os.path.join(tempfile.gettempdir(),
                        "quadruped_fastdds_%s.xml" % local_ip.replace(".", "_"))
    xml = """<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by launcher.py. Restricts FastDDS to %s. -->
<dds>
  <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>iface_udp</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>%s</address>
        </interfaceWhiteList>
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="iface_only" is_default_profile="true">
      <rtps>
        <userTransports><transport_id>iface_udp</transport_id></userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
""" % (local_ip, local_ip)
    try:
        with open(path, "w") as f:
            f.write(xml)
        return path
    except Exception:
        return None


def ckpt_display_name(path):
    """Extract the run folder name from a full checkpoint path."""
    parts = path.replace("\\", "/").split("/")
    for i, p in enumerate(parts):
        if p == "checkpoints" and i > 0:
            return parts[i - 1]
    return os.path.join(*parts[-3:-1]) if len(parts) >= 3 else path

def save_last_command(data):
    try:
        with open(LAST_COMMAND_FILE, "w") as f:
            json.dump(data, f)
    except Exception:
        pass

def load_last_command():
    if os.path.exists(LAST_COMMAND_FILE):
        try:
            with open(LAST_COMMAND_FILE, "r") as f:
                return json.load(f)
        except Exception:
            pass
    return None

def resolve_phase_launcher(all_phases, phase_name):
    import collections.abc
    import copy
    
    def deep_update(d, u):
        if not isinstance(d, collections.abc.Mapping):
            d = {}
        if not isinstance(u, collections.abc.Mapping):
            return d
        for k, v in u.items():
            if v is None:
                continue
            if isinstance(v, collections.abc.Mapping):
                target = d.get(k, {})
                if not isinstance(target, collections.abc.Mapping):
                    target = {}
                d[k] = deep_update(target, v)
            else:
                d[k] = v
        return d

    phase_node = all_phases.get("phases", {}).get(phase_name, {})
    parent_name = phase_node.get("inherits", "default")
    
    if parent_name and parent_name != phase_name:
        if parent_name == "default":
            parent_cfg = all_phases.get("default", {})
        else:
            parent_cfg = resolve_phase_launcher(all_phases, parent_name)
    else:
        parent_cfg = all_phases.get("default", {})

    return deep_update(copy.deepcopy(parent_cfg), phase_node)

def compute_all_curriculum_segments(yaml_data, available_phases, start_phase):
    if not yaml_data or "phases" not in yaml_data or start_phase not in available_phases:
        return [start_phase]
    
    start_idx = available_phases.index(start_phase)
    phases_to_check = available_phases[start_idx:]
    
    segments = []
    curr_seg_start = phases_to_check[0]
    curr_seg_end = phases_to_check[0]
    
    start_cfg = resolve_phase_launcher(yaml_data, curr_seg_start)
    start_env = start_cfg.get("env", {})
    curr_robot = start_env.get("robot_cfg", "")
    curr_terrain = start_env.get("terrain", "rough")
    
    for k in phases_to_check[1:]:
        cfg = resolve_phase_launcher(yaml_data, k)
        env = cfg.get("env", {})
        robot = env.get("robot_cfg", "")
        terrain = env.get("terrain", "rough")
        
        if robot == curr_robot and terrain == curr_terrain:
            curr_seg_end = k
        else:
            if curr_seg_start != curr_seg_end:
                segments.append(f"{curr_seg_start}_to_{curr_seg_end}")
            else:
                segments.append(curr_seg_start)
            curr_seg_start = k
            curr_seg_end = k
            curr_robot = robot
            curr_terrain = terrain
            
    if curr_seg_start != curr_seg_end:
        segments.append(f"{curr_seg_start}_to_{curr_seg_end}")
    else:
        segments.append(curr_seg_start)
        
    return segments

def rename_latest_run_dir(log_root, start_timestamp, target_name, existing_dirs=None):
    if not os.path.exists(log_root):
        return None
    
    candidates = []
    for d in os.listdir(log_root):
        if existing_dirs is not None and d in existing_dirs:
            continue
        full_path = os.path.join(log_root, d)
        if os.path.isdir(full_path):
            try:
                mtime = os.path.getmtime(full_path)
                ctime = os.path.getctime(full_path)
                if existing_dirs is not None or max(mtime, ctime) >= start_timestamp:
                    candidates.append((max(mtime, ctime), d, full_path))
            except Exception:
                pass
                
    if not candidates:
        return None
        
    candidates.sort(key=lambda x: x[0], reverse=True)
    latest_dir_name, latest_full_path = candidates[0][1], candidates[0][2]
    
    if not target_name or latest_dir_name == target_name:
        return os.path.abspath(latest_full_path)
        
    dest_path = os.path.join(log_root, target_name)
    if dest_path == latest_full_path:
        return os.path.abspath(dest_path)
        
    if os.path.exists(dest_path):
        idx = 2
        while os.path.exists(f"{dest_path}_{idx}"):
            idx += 1
        dest_path = f"{dest_path}_{idx}"
        
    try:
        os.rename(latest_full_path, dest_path)
        print(f"[Launcher] Renamed run directory from '{latest_dir_name}' to '{os.path.basename(dest_path)}'")
        return os.path.abspath(dest_path)
    except Exception as e:
        print(f"[WARNING] Could not rename '{latest_dir_name}' to '{os.path.basename(dest_path)}': {e}")
        return os.path.abspath(latest_full_path)

def find_highest_step_checkpoint(run_dir):
    if not run_dir or not os.path.exists(run_dir):
        return None
        
    search_pattern = os.path.join(run_dir, "**", "*.pt")
    all_pts = glob.glob(search_pattern, recursive=True)
    
    if not all_pts:
        return None
        
    numbered_ckpts = []
    for pt in all_pts:
        base = os.path.basename(pt)
        if base.startswith("agent_") and base.endswith(".pt") and base != "best_agent.pt":
            num_str = ''.join(filter(str.isdigit, base))
            if num_str:
                try:
                    numbered_ckpts.append((int(num_str), pt))
                except ValueError:
                    pass
                    
    if numbered_ckpts:
        numbered_ckpts.sort(key=lambda x: x[0], reverse=True)
        max_step, best_path = numbered_ckpts[0]
        print(f"[Launcher] Found latest curriculum checkpoint: {os.path.basename(best_path)} (step {max_step})")
        return os.path.abspath(best_path)
        
    best_agents = [p for p in all_pts if os.path.basename(p) == "best_agent.pt"]
    if best_agents:
        print(f"[Launcher] No numbered checkpoint found, falling back to: {os.path.basename(best_agents[0])}")
        return os.path.abspath(best_agents[0])
        
    return os.path.abspath(all_pts[0]) if all_pts else None

def run_cli_menu():
    is_isaac = "env_isaacsim" in os.environ.get("VIRTUAL_ENV", "") or "env_isaacsim" in sys.executable
    is_robot = IS_ROBOT

    print("\n" + "=" * 50)
    print(" Quadruped Unified Launcher")
    print("=" * 50)
    
    if is_robot:
        print(" [HARDWARE]    Physical Robot (ARM64)")
    else:
        print(" [HARDWARE]    Remote PC/VDI (AMD64)")

    if IS_DOCKER:
        print(" [ENVIRONMENT] Docker Container Detected")
        print("               (IsaacLab options disabled)")
    elif is_isaac:
        print(" [ENVIRONMENT] IsaacSim Native Environment Detected")
    else:
        print(" [ENVIRONMENT] Host Native Environment")
        
    print("=" * 50 + "\n")

    # 1. Action Selection
    last_cmd = load_last_command()
    print("Select Action:")
    if last_cmd:
        print(f"  [0] Repeat Last: {last_cmd.get('action')} on {last_cmd.get('module_name')}")
        print("  " + "-" * 45)
    
    if not IS_DOCKER:
        print("  [1] Train Policy")
        print("  [2] Play IsaacLab")
        print("  " + "-" * 45)
        print("  [3] Play IsaacSim")
    else:
        print("  [X] Train Policy (AVAILABLE ONLY ON ISAACSIM VENV)")
        print("  [X] Play IsaacLab (AVAILABLE ONLY ON ISAACSIM VENV)")
        print("  " + "-" * 45)
        print("  [X] Play IsaacSim (AVAILABLE ONLY ON ISAACSIM VENV)")
        

    # Detect if we are in an environment that CANNOT run ROS 2 Humble natively
    requires_docker = not IS_DOCKER and sys.version_info[:2] != (3, 10)
    
    if not requires_docker:
        print("  [4] Play MuJoCo")
        print("  [5] Play Gazebo")
        print("  [6] Deploy to Robot")
        print("  [7] Evaluate Policy (MuJoCo)")
        print("  " + "-" * 45)
        print("  [C] Console")
        print("  [T] Test Joints (Real Robot)")
        print("  " + "-" * 45)
        print("  --- ROS 2 Tools ---")
        print("  [K] Remote Teleop")
        print("  [V] Visualizers")
        print("  [P] PlotJuggler")
        print("  [M] MCAP Log & Replay")
        print("  [R] RQT Graph")
        print("  [F] TF2 Tree")
        print("  [D] Discovery Server (needed for ROS 2 over WiFi)")
    else:
        print("  [X] Play MuJoCo (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Play Gazebo (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Deploy to Robot (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Evaluate Policy (REQUIRES DOCKER OR PY3.10)")
        print("  " + "-" * 45)
        print("  [X] Console (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Test Joints (Real Robot) (REQUIRES DOCKER OR PY3.10)")
        print("  " + "-" * 45)
        print("  --- ROS 2 Tools ---")
        print("  [X] Remote Teleop (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Visualizers (REQUIRES DOCKER OR PY3.10)")
        print("  [X] PlotJuggler (REQUIRES DOCKER OR PY3.10)")
        print("  [X] MCAP Log & Replay (REQUIRES DOCKER OR PY3.10)")
        print("  [X] RQT Graph (REQUIRES DOCKER OR PY3.10)")
        print("  [X] TF2 Tree (REQUIRES DOCKER OR PY3.10)")
        print("  [X] Discovery Server (REQUIRES DOCKER OR PY3.10)")

    action_map = {
        "0": "repeat",
        "1": "train",
        "2": "isaac_lab",
        "3": "isaac_sim",
        "4": "mujoco",
        "5": "gazebo",
        "6": "real_deploy",
        "7": "eval_policy",
        "k": "teleop",
        "K": "teleop",
        "v": "visualizers",
        "V": "visualizers",
        "c": "console",
        "C": "console",
        "t": "hardware_tools",
        "T": "hardware_tools",
        "p": "plotjuggler",
        "P": "plotjuggler",
        "m": "mcap",
        "M": "mcap",
        "r": "rqt_graph",
        "R": "rqt_graph",
        "f": "tf2_tree",
        "F": "tf2_tree",
        "d": "discovery_server",
        "D": "discovery_server",
    }
    
    default_action = "0" if last_cmd else "4"
    if requires_docker and default_action == "4":
        default_action = "None" # No valid default if MuJoCo is blocked

    choice = input(f"Enter choice [0-7, K, V, C, T, P, M, R, F, D] (default {default_action}): ").strip() or default_action
    action = action_map.get(choice.lower(), "None")
    
    if action == "hardware_tools":
        print("\n--- Hardware Tools ---")
        print("  [1] Telemetry Only (Real Driver, No Policy)")
        print("  [2] Joint Tester (Sine Wave Oscillation)")
        hw_choice = input("Enter choice [1-2] (default 1): ").strip() or "1"
        if hw_choice == "2":
            action = "test_joints"
        else:
            action = "real_telemetry"
            
    if action == "teleop":
        tel_choice = input("Select Teleop [1: Keyboard, 2: Gamepad (Joy)] (default 1): ").strip() or "1"
        if tel_choice == "2":
            action = "teleop_joy"
        else:
            action = "teleop_keyboard"
            
    if action == "visualizers":
        vis_choice = input("Select Visualizer [1: MuJoCo Twin, 2: Gazebo Twin, 3: RViz, 4: Foxglove] (default 1): ").strip() or "1"
        if vis_choice == "4":
            action = "foxglove"
        elif vis_choice == "3":
            action = "rviz"
        elif vis_choice == "2":
            action = "gazebo_twin"
        else:
            action = "mujoco_twin"
    
    # 1.1 Handle Repeat
    if action == "repeat" and last_cmd:
        # Load with defaults to avoid KeyError on old config files
        action = last_cmd.get("action", "mujoco")
        
        # Enforce Docker restrictions even on repeated commands
        if IS_DOCKER and action in ["train", "isaac_lab", "isaac_sim"]:
            print(f"\n[WARNING] Last action '{action}' is not available in Docker. Switching to MuJoCo.")
            action = "mujoco"
        
        if not IS_DOCKER and action in ["mujoco", "gazebo", "real_deploy", "real_telemetry", "mujoco_twin", "gazebo_twin", "rviz", "foxglove", "console", "test_joints", "mcap_record", "mcap_replay_rosbag", "mcap_replay_interactive", "teleop_keyboard", "teleop_joy", "rqt_graph", "tf2_tree", "discovery_server"]:
            if sys.version_info[:2] != (3, 10):
                print(f"\n[ERROR] Last action '{action}' requires Python 3.10 or Docker. Aborting.")
                sys.exit(1)

        return (
            last_cmd.get("module_name", "None"),
            last_cmd.get("module_path", "."),
            action,
            last_cmd.get("robot_cfg", "UNITREE_GO2_CFG"),
            last_cmd.get("terrain_cfg", "flat"),
            last_cmd.get("num_envs", "1"),
            last_cmd.get("ckpt"),
            last_cmd.get("teleop", False),
            last_cmd.get("headless", IS_DOCKER),
            last_cmd.get("video", False),
            last_cmd.get("run_name", ""),
            last_cmd.get("domain_id", "1"),
            last_cmd.get("use_estimator", False),
            last_cmd.get("record_session", False),
            last_cmd.get("training_phase", ""),
        )

    # 1.2 Validation
    if IS_DOCKER and choice in ["1", "2", "3"]:
        print("\n[ERROR] Training/IsaacSim actions are not available in Docker. Aborting.")
        sys.exit(1)
        
    if requires_docker and choice.lower() in ["4", "5", "6", "7", "k", "v", "c", "t", "p", "m", "r", "f"]:
        print(f"\n[ERROR] Action '{action}' requires ROS 2 Humble (Python 3.10).")
        print("        Please run this task inside DOCKER or switch to a 3.10 environment.")
        sys.exit(1)

    print(f"\n--- Selected Action: {action.upper()} ---\n")
    
    # Rename Terminator window pane based on action and environment
    try:
        if IS_ROBOT:
            env_str = "ROBOT"
        elif IS_DOCKER:
            env_str = "DOCKER"
        elif is_isaac:
            env_str = "ISAAC"
        else:
            env_str = "HOST"
            
        sys.stdout.write(f"\x1b]2;[{env_str}] {action.upper()}\x07")
        sys.stdout.flush()
    except Exception:
        pass

    # 2. Module Selection
    selected_module_name = "None"
    selected_module_path = "."
    
    if action not in ["mujoco_twin", "gazebo_twin", "rviz", "foxglove", "console", "teleop", "teleop_keyboard", "teleop_joy", "test_joints", "real_telemetry", "plotjuggler", "mcap", "rqt_graph", "tf2_tree", "discovery_server"]:
        modules = sorted([d for d in os.listdir(TASKS_DIR) if os.path.isdir(os.path.join(TASKS_DIR, d))])
        
        if not modules:
            print(f"[ERROR] No modules found in {TASKS_DIR}!")
            sys.exit(1)

        print("Select Module:")
        for i, m in enumerate(modules):
            print(f"  [{i+1}] {m}")
        
        module_choice = input(f"Enter choice [1-{len(modules)}] (default 1): ").strip() or "1"
        try:
            selected_module_name = modules[int(module_choice) - 1]
        except (ValueError, IndexError):
            selected_module_name = modules[0]

        selected_module_path = os.path.join(TASKS_DIR, selected_module_name)
        print(f"\n--- Operating on {selected_module_name} ---\n")

    # 3. Checkpoint Selection (Agent)
    # Search for any .pt files in logs folder recursively
    search_pattern = os.path.join(selected_module_path, "logs", "**", "*.pt")
    checkpoint_paths = glob.glob(search_pattern, recursive=True)
    
    # Also check a 'checkpoints' folder at the module root just in case
    checkpoint_paths += glob.glob(os.path.join(selected_module_path, "checkpoints", "*.pt"))
    
    # Filter to only show 'best_agent.pt'
    all_ckpts = [p for p in checkpoint_paths if os.path.basename(p) == "best_agent.pt"]
    all_ckpts.sort(reverse=True)
    selected_ckpt = None

    if action not in ["teleop", "teleop_keyboard", "teleop_joy", "mujoco_twin", "gazebo_twin", "rviz", "foxglove", "console", "test_joints", "real_telemetry", "plotjuggler", "mcap", "rqt_graph", "tf2_tree", "discovery_server"]:
        print("\nSelect Trained Checkpoint (Agent):")
        if action == "train":
            print("  [0] Train from Scratch (None)")
        
        if not all_ckpts:
            print(f"  [X] No checkpoints found automatically in:")
            print(f"      - {os.path.join(selected_module_path, 'logs/')}")
            print(f"      - {os.path.join(selected_module_path, 'checkpoints/')}")
        
        for i, path in enumerate(all_ckpts):
            print(f"  [{i+1}] {ckpt_display_name(path)} ({os.path.basename(path)})")
        
        print("  [M] Enter Manual Path")
        
        default_val = "0" if action == "train" else ("1" if all_ckpts else "M")
        ckpt_choice = input(f"Enter choice [0-{len(all_ckpts)} or M] (default {default_val}): ").strip() or default_val
        
        if ckpt_choice.lower() == "m":
            selected_ckpt = input("Enter full path to .pt file: ").strip()
        elif ckpt_choice == "0" and action == "train":
            selected_ckpt = None
        else:
            try:
                selected_ckpt = all_ckpts[int(ckpt_choice) - 1]
            except (ValueError, IndexError):
                selected_ckpt = all_ckpts[0] if all_ckpts else None

    if selected_ckpt:
        ckpt_dir = os.path.dirname(selected_ckpt)
        other_ckpts = glob.glob(os.path.join(ckpt_dir, "*.pt"))
        if len(other_ckpts) > 1:
            print(f"\nSelect Specific Checkpoint from this Run:")
            
            def extract_step(filepath):
                base = os.path.basename(filepath)
                if base == "best_agent.pt": return float('inf')
                try:
                    return int(''.join(filter(str.isdigit, base)))
                except ValueError:
                    return -1
                    
            other_ckpts.sort(key=extract_step, reverse=True)
            
            for i, p in enumerate(other_ckpts):
                print(f"  [{i+1}] {os.path.basename(p)}")
                
            sub_choice = input(f"Enter choice [1-{len(other_ckpts)}] (default 1): ").strip() or "1"
            try:
                selected_ckpt = other_ckpts[int(sub_choice) - 1]
            except (ValueError, IndexError):
                selected_ckpt = other_ckpts[0]
                
        print(f"[Launcher] Selected agent: {selected_ckpt}")

    # 4. Environment & Options
    # Load default domain from config.yaml
    default_domain = "1"
    try:
        with open(CONFIG_PATH, 'r') as f:
            cfg_data = yaml.safe_load(f)
            default_domain = str(cfg_data.get("network", {}).get("ros_domain_id", "1"))
    except Exception:
        pass

    domain_id = default_domain
    if action not in ["train", "isaac_lab", "eval_policy", "discovery_server"]:
        domain_id = input(f"Enter ROS_DOMAIN_ID (default {default_domain}): ").strip() or default_domain
    robot_cfg = "UNITREE_GO2_CFG" # Default for now
    terrain_cfg = "flat"
    num_envs = 1
    headless = IS_ROBOT
    video = False
    teleop = False
    if action in ["mujoco", "gazebo", "real_deploy", "isaac_sim"]:
        teleop = True # Always active internally via /cmd_vel subscription
    run_name = ""
    use_estimator = False
    training_phase = ""

    if action in ["train", "isaac_lab", "eval_policy", "isaac_sim", "mujoco", "gazebo"]:
        if action in ["isaac_sim", "mujoco", "gazebo", "eval_policy"]:
            robot_choice = input("Select Robot [1: Go2, 2: Go1, 3: A1] (default 1): ").strip() or "1"
            robot_cfg = {"1": "UNITREE_GO2_CFG", "2": "UNITREE_GO1_CFG", "3": "UNITREE_A1_CFG"}.get(robot_choice, "UNITREE_GO2_CFG")
        elif action in ["isaac_lab"]:
            robot_choice = input("Select Robot [1: Go2, 2: Go1, 3: A1, 4: All (Mixed)] (default 1): ").strip() or "1"
            robot_cfg = {"1": "UNITREE_GO2_CFG", "2": "UNITREE_GO1_CFG", "3": "UNITREE_A1_CFG", "4": "RANDOM"}.get(robot_choice, "UNITREE_GO2_CFG")
        else:
            robot_cfg = "RANDOM" # Will be overridden by YAML or fallback to default
        
        if action in ["isaac_lab"]:
            terrain_choice = input("Select Terrain [1: flat, 2: rough] (default 1): ").strip() or "1"
            terrain_cfg = "rough" if terrain_choice == "2" else "flat"
        else:
            terrain_cfg = ""
        
        if action == "train":
            num_envs = input("Number of Envs (Enter to use YAML, or type number): ").strip() or ""
        else:
            num_envs = input("Number of Envs (default 1): ").strip() or "1"
        
        if not IS_ROBOT:
            headless = input("Headless Mode? [y/N]: ").lower().strip() == "y"
        
        if action == "train":
            # Dynamically extract phases from training_phases.yaml if available
            available_phases = ["phase1", "phase2", "phase3"] # fallback
            default_phase_idx = "3"
            
            # Search only in the source directory to avoid picking up backups in logs/
            source_dir = os.path.join(selected_module_path, "source")
            yaml_files = glob.glob(os.path.join(source_dir, "**", "training_phases.yaml"), recursive=True)
            yaml_data = {}
            if yaml_files:
                try:
                    with open(yaml_files[0], 'r') as f:
                        yaml_data = yaml.safe_load(f)
                        if "phases" in yaml_data:
                            extracted_phases = list(yaml_data["phases"].keys())
                            if extracted_phases:
                                available_phases = extracted_phases
                                default_phase_idx = str(len(available_phases))
                except Exception:
                    pass
                    
            phase_options_str = ", ".join([f"{i+1}: {p}" for i, p in enumerate(available_phases)])
            phase_choice = input(f"Select Training Phase [{phase_options_str}] (default {default_phase_idx}): ").strip() or default_phase_idx
            
            try:
                phase_idx = int(phase_choice) - 1
                training_phase = available_phases[phase_idx] if 0 <= phase_idx < len(available_phases) else f"phase{phase_choice}"
            except ValueError:
                training_phase = phase_choice
                
            # Curriculum sequence logic
            all_segments = compute_all_curriculum_segments(yaml_data, available_phases, training_phase)
            first_segment = all_segments[0] if all_segments else training_phase
            
            if first_segment != training_phase:
                ans = input(f"Run as Curriculum Sequence ({training_phase} up to {first_segment.split('_to_')[-1]})? [y/N]: ").lower().strip()
                if ans == "y":
                    training_phase = first_segment
                
            training_segments = [training_phase]
            if len(all_segments) > 1 and training_phase == first_segment:
                next_segments_str = ", ".join(all_segments[1:])
                ans_chain = input(f"Auto-launch remaining curriculum segments sequentially ({next_segments_str})? [Y/n]: ").lower().strip()
                if ans_chain != "n":
                    training_segments = all_segments
                    training_phase = training_segments
                
            run_name = input("Enter Run Name (optional): ").strip()
            video = input("Record Video? [y/N]: ").lower().strip() == "y"
            
        if action == "isaac_lab":
            ans = input("Enable Manual Keyboard Control? [y/N]: ").lower().strip()
            if ans == "y":
                teleop = True

    if action in ["mujoco", "gazebo", "real_deploy"]:
        if not IS_ROBOT and action != "real_deploy":
            headless = input("Headless Mode? [y/N]: ").lower().strip() == "y"

    if action in ["mujoco", "gazebo", "isaac_sim"]:
        ans = input("Use State Estimator? [Y/n] (default Y): ").lower().strip()
        use_estimator = ans != "n"

    # Auto-record prompt if launching driver
    record_session = False
    if action in ["mujoco", "gazebo", "isaac_sim", "real_deploy"]:
        # First check config default
        cfg_auto = False
        try:
            with open(CONFIG_PATH, 'r') as f:
                cfg_data = yaml.safe_load(f)
                cfg_auto = cfg_data.get("logging", {}).get("auto_record", False)
        except Exception:
            pass
        
        default_prompt = "Y/n" if cfg_auto else "y/N"
        ans = input(f"Record this session to MCAP? [{default_prompt}]: ").lower().strip()
        if ans == "":
            record_session = cfg_auto
        else:
            record_session = (ans == "y")

    if action == "mcap":
        # MCAP Log & Replay sub-menu
        print("\n--- MCAP Telemetry Manager ---")
        print("  [WARNING] If you started MuJoCo, Gazebo, IsaacSim, or Deploy with auto-record enabled, it is already recording!")
        print("  [1] Record Topics (Ros2 Bag)")
        print("  [2] Replay (Ros2 Bag)")
        print("  [3] Replay (Custom Script)")
        mcap_choice = input("Enter choice [1-3] (default 3): ").strip() or "3"
        
        # Load record_dir from config
        record_dir = "Mcap/Recordings"
        try:
            with open(CONFIG_PATH, 'r') as f:
                cfg_data = yaml.safe_load(f)
                record_dir = cfg_data.get("logging", {}).get("record_dir", "Mcap/Recordings")
        except Exception:
            pass
            
        os.makedirs(record_dir, exist_ok=True)

        if mcap_choice == "1":
            action = "mcap_record"
            filename = input("Enter output directory name (optional, e.g. run1): ").strip()
            if not filename:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"run_{timestamp}"
            run_name = os.path.join(record_dir, filename)
        else:
            if mcap_choice == "2":
                action = "mcap_replay_rosbag"
            else:
                action = "mcap_replay_interactive"
                
            # List files and directories
            items = sorted(os.listdir(record_dir))
            files = []
            for item in items:
                full_path = os.path.join(record_dir, item)
                if item.endswith(".mcap") or os.path.isdir(full_path):
                    files.append(item)

            if not files:
                print(f"[Launcher] No recorded sessions found in '{record_dir}/'.")
                sys.exit(0)
            print("\nSelect Session to Play Back:")
            for i, f in enumerate(files):
                print(f"  [{i+1}] {f}")
            f_choice = input(f"Enter choice [1-{len(files)}] (default 1): ").strip() or "1"
            try:
                selected_file = files[int(f_choice) - 1]
            except (ValueError, IndexError):
                selected_file = files[0]
            run_name = os.path.join(record_dir, selected_file)

    return selected_module_name, selected_module_path, action, robot_cfg, terrain_cfg, num_envs, selected_ckpt, teleop, headless, video, run_name, domain_id, use_estimator, record_session, training_phase

def main():
    (
        module_name,
        module_path,
        action,
        robot_cfg,
        terrain_cfg,
        num_envs,
        ckpt,
        teleop,
        headless,
        video,
        run_name,
        domain_id,
        use_estimator,
        record_session,
        training_phase,
    ) = run_cli_menu()

    # Save for next time
    save_last_command({
        "module_name": module_name,
        "module_path": module_path,
        "action": action,
        "robot_cfg": robot_cfg,
        "terrain_cfg": terrain_cfg,
        "num_envs": num_envs,
        "ckpt": ckpt,
        "teleop": teleop,
        "headless": headless,
        "video": video,
        "run_name": run_name,
        "domain_id": domain_id,
        "use_estimator": use_estimator,
        "record_session": record_session,
        "training_phase": training_phase,
    })

    print("\n" + "=" * 50)
    print(f"Launching {action.upper()} Mode for {module_name}!")
    print(f"Robot:    {robot_cfg}")
    if action in ["isaac_lab"]:
        print(f"Terrain:  {terrain_cfg}")
    print(f"Domain ID: {domain_id}")
    if training_phase:
        display_phase = ", ".join(training_phase) if isinstance(training_phase, list) else str(training_phase)
        print(f"Phase:    {display_phase}")
    if ckpt:
        print(f"Checkpoint: {ckpt_display_name(ckpt)}")
    print(f"Teleop:   {teleop}")
    print("=" * 50 + "\n")

    # Set up environment variables
    env = os.environ.copy()
    env["ROS_DOMAIN_ID"] = str(domain_id)

    # ROS 2 discovery: multicast on cable, discovery server over the robot's WiFi AP.
    discovery_server, discovery_local_ip = resolve_discovery_server()
    if discovery_server:
        env["ROS_DISCOVERY_SERVER"] = discovery_server
        # Without this the CLI only sees topics it matched itself, so `ros2 topic
        # list` looks broken even when discovery is working.
        env["ROS_SUPER_CLIENT"] = "TRUE"
        print(f"[Launcher] Wireless path detected -> ROS_DISCOVERY_SERVER={discovery_server}")
        profile = write_fastdds_profile(discovery_local_ip)
        if profile:
            env["FASTRTPS_DEFAULT_PROFILES_FILE"] = profile
            print(f"[Launcher] FastDDS pinned to {discovery_local_ip} ({profile})")
        print(f"[Launcher] Requires 'fast-discovery-server -i 0 -l {discovery_server.replace(':', ' -p ')}' on the robot.")
    else:
        # Be authoritative: a stale export from a previous wireless session would
        # otherwise break discovery once you are back on cable.
        env.pop("ROS_DISCOVERY_SERVER", None)
        env.pop("ROS_SUPER_CLIENT", None)
        # Only drop a profile we generated - never a hand-picked one.
        if "quadruped_fastdds_" in env.get("FASTRTPS_DEFAULT_PROFILES_FILE", ""):
            env.pop("FASTRTPS_DEFAULT_PROFILES_FILE", None)

    if (discovery_server or None) != (os.environ.get("ROS_DISCOVERY_SERVER") or None):
        # The daemon caches the previous discovery view across cable/WiFi switches.
        try:
            subprocess.run(["ros2", "daemon", "stop"], env=env, timeout=10,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception:
            pass
    env["QUADRUPED_ROBOT_CFG"] = robot_cfg
    env["QUADRUPED_ROBOT"] = robot_cfg
    if teleop:
        env["QUADRUPED_TELEOP"] = "1"
    if training_phase:
        env["QUADRUPED_TRAINING_PHASE"] = ", ".join(training_phase) if isinstance(training_phase, list) else str(training_phase)
    
    # Search for OBS_DIM in the same folder as the checkpoint
    if ckpt:
        ckpt_dir = os.path.dirname(ckpt)
        params_dir = os.path.abspath(os.path.join(ckpt_dir, "..", "params"))
        agent_cfg = os.path.join(params_dir, "agent.yaml")
        env_cfg_path = os.path.join(params_dir, "env.yaml")
        obs_dim = 0
        
        # Try agent.yaml first
        if os.path.exists(agent_cfg):
            try:
                with open(agent_cfg, 'r') as f:
                    data = yaml.load(f, Loader=yaml.UnsafeLoader)
                    obs_dim = data.get("models", {}).get("policy", {}).get("input_shape", [0])[0]
            except Exception:
                pass
                
        # Try env.yaml if not found in agent.yaml
        if not obs_dim and os.path.exists(env_cfg_path):
            try:
                with open(env_cfg_path, 'r') as f:
                    data = yaml.load(f, Loader=yaml.UnsafeLoader)
                    obs_dim = data.get("observation_space", 0)
            except Exception:
                pass
                
        if obs_dim:
            env["QUADRUPED_OBS_DIM"] = str(obs_dim)
            print(f"[INFO] Detected observation dimension from checkpoint: {obs_dim}")

    # Prepare environment
    if terrain_cfg:
        env["QUADRUPED_TERRAIN"] = terrain_cfg

    # Inject the task module's source directory into PYTHONPATH so that Quadruped.tasks can be imported
    source_path = os.path.abspath(os.path.join(module_path, "source", "Quadruped"))
    if os.path.exists(source_path):
        current_pythonpath = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = f"{source_path}:{current_pythonpath}" if current_pythonpath else source_path

    # Final Command Assembly
    abs_ckpt = os.path.abspath(ckpt) if ckpt else ""
    obs_dim = env.get("QUADRUPED_OBS_DIM", "51")

    def get_robot_key(cfg):
        return {
            "UNITREE_A1_CFG": "a1",
            "UNITREE_GO1_CFG": "go1",
            "UNITREE_GO2_CFG": "go2",
        }.get(cfg or "", "go2")

    robot_key = get_robot_key(robot_cfg)

    if action == "train":
        script_path = os.path.join("scripts", "skrl", "train.py")
        log_root = os.path.join(module_path, "logs", "skrl", "quadruped_direct")
        
        if isinstance(training_phase, list):
            segments = training_phase
        else:
            segments = [training_phase] if training_phase else [""]
            
        current_ckpt = abs_ckpt
        
        for seg_idx, segment in enumerate(segments):
            if len(segments) > 1:
                print("\n" + "=" * 50)
                print(f"Executing Curriculum Segment {seg_idx + 1}/{len(segments)}: {segment}")
                print("=" * 50 + "\n")
                
            seg_env = env.copy()
            if segment:
                seg_env["QUADRUPED_TRAINING_PHASE"] = segment
                
            cmd = [sys.executable, script_path, "--task=Template-Quadruped-Direct-v0"]
            if num_envs:
                cmd.append(f"--num_envs={num_envs}")
            if current_ckpt:
                cmd.append(f"--checkpoint={current_ckpt}")
            if headless:
                cmd.append("--headless")
            if video:
                cmd.append("--video")
                cmd.append("--video_length=200")
                cmd.append("--video_interval=5000")
                
            target_run_name = run_name
            if len(segments) > 1 and run_name:
                target_run_name = f"{run_name}_{segment}"
            elif len(segments) > 1 and not run_name and segment:
                target_run_name = segment
                
            if target_run_name:
                cmd.append(f"agent.agent.experiment.experiment_name={target_run_name}")
                
            start_ts = time.time()
            existing_dirs = set(os.listdir(log_root)) if os.path.exists(log_root) else set()
            try:
                res = subprocess.run(cmd, env=seg_env, cwd=module_path)
            except KeyboardInterrupt:
                print("\n[Launcher] Training interrupted by user.")
                break
                
            renamed_path = rename_latest_run_dir(log_root, start_ts, target_run_name, existing_dirs=existing_dirs)
            next_ckpt = find_highest_step_checkpoint(renamed_path) if renamed_path else None
            
            if res.returncode != 0:
                if not next_ckpt:
                    print(f"\n[Launcher] Training segment '{segment}' exited with return code {res.returncode} without generating valid checkpoints. Aborting chain.")
                    break
                else:
                    print(f"\n[WARNING] Training segment '{segment}' exited with return code {res.returncode} (likely during Isaac Sim/carb shutdown cleanup), but successfully saved checkpoints ({os.path.basename(next_ckpt)}). Continuing chain...")
            
            if seg_idx < len(segments) - 1:
                if not next_ckpt:
                    print(f"[ERROR] Could not find any valid checkpoint in '{renamed_path}' to continue curriculum. Aborting chain.")
                    break
                current_ckpt = os.path.abspath(next_ckpt)

    elif action == "isaac_lab":
        script_path = os.path.join("scripts", "skrl", "play.py")
        cmd = [sys.executable, script_path, "--task=Template-Quadruped-Direct-v0"]
        if num_envs:
            cmd.append(f"--num_envs={num_envs}")
        if ckpt:
            cmd.append(f"--checkpoint={abs_ckpt}")
        if headless:
            cmd.append("--headless")
        subprocess.run(cmd, env=env, cwd=module_path)

    elif action in ("eval_policy", "mujoco", "gazebo", "isaac_sim", "real_deploy", "real_telemetry", "mujoco_twin", "gazebo_twin", "rviz", "foxglove", "console", "teleop_keyboard", "teleop_joy", "test_joints", "plotjuggler", "mcap_record", "mcap_replay_rosbag", "mcap_replay_interactive", "rqt_graph", "tf2_tree", "discovery_server"):
        # Unified Driver Pipeline
        isaac_python = os.path.expanduser("~/env_isaacsim/bin/python")
        sys_python = sys.executable 

        if action == "eval_policy":
            bridge_script = os.path.abspath(os.path.join("Mujoco", "eval_mujoco.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
                f"--internal_policy={abs_ckpt}",
                f"--obs_dim={obs_dim}",
            ]
            if headless:
                cmd.append("--headless")
            if use_estimator:
                cmd.append("--use_estimator")


        if action == "isaac_sim":
            bridge_script = os.path.abspath(os.path.join("IsaacSim", "isaac_driver.py"))
            cmd = [
                isaac_python,
                bridge_script,
                f"--robot={robot_key}",
                f"--internal_policy={abs_ckpt}",
                f"--obs_dim={obs_dim}",
            ]
            if use_estimator:
                cmd.append("--use_estimator")
        elif action == "mujoco":
            bridge_script = os.path.abspath(os.path.join("Mujoco", "mujoco_driver.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
                f"--internal_policy={abs_ckpt}",
                f"--obs_dim={obs_dim}",
            ]
            # Automatically enable headless in Docker or if headless flag is set
            if headless:
                cmd.append("--headless")
            if use_estimator:
                cmd.append("--use_estimator")
        elif action == "mujoco_twin":
            bridge_script = os.path.abspath(os.path.join("Operator", "mujoco_twin.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
            ]
            if use_estimator:
                cmd.append("--use_estimator")
        elif action == "gazebo_twin":
            bridge_script = os.path.abspath(os.path.join("Operator", "gazebo_twin.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
            ]
            if use_estimator:
                cmd.append("--use_estimator")
        elif action == "rviz":
            cmd = ["ros2", "run", "rviz2", "rviz2"]
        elif action == "console":
            bridge_script = os.path.abspath(os.path.join("Operator", "console.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
            ]
            if use_estimator:
                cmd.append("--use_estimator")
        elif action == "gazebo":
            bridge_script = os.path.abspath(os.path.join("Gazebo", "gazebo_driver.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
                f"--internal_policy={abs_ckpt}",
                f"--obs_dim={obs_dim}",
            ]
            if use_estimator:
                cmd.append("--use_estimator")
        elif action in ["real_deploy", "real_telemetry"]:
            bridge_script = os.path.abspath(os.path.join("Unitree", "real_driver.py"))
            cmd = [
                sys_python,
                bridge_script,
                f"--robot={robot_key}",
                f"--obs_dim={obs_dim}",
            ]
            if action == "real_deploy" and abs_ckpt:
                cmd.append(f"--internal_policy={abs_ckpt}")

        elif action == "teleop_keyboard":
            cmd = ["ros2", "run", "teleop_twist_keyboard", "teleop_twist_keyboard"]
            # No robot_key or ckpt needed for this
            
        elif action == "teleop_joy":
            cmd = ["ros2", "launch", "teleop_twist_joy", "teleop-launch.py"]

        elif action == "test_joints":
            bridge_script = os.path.abspath(os.path.join("Unitree", "test_joints.py"))
            cmd = [sys_python, bridge_script]
        
        elif action == "plotjuggler":
            cmd = ["ros2", "run", "plotjuggler", "plotjuggler"]
            
        elif action == "foxglove":
            cmd = ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml"]

        elif action == "discovery_server":
            # Replaces multicast discovery, which the robot's WiFi AP drops.
            # Must be running before any node that has ROS_DISCOVERY_SERVER set,
            # otherwise discovery fails outright instead of falling back.
            host, _, port = discovery_server_address().partition(":")
            addrs = subprocess.run(["hostname", "-I"], capture_output=True, text=True).stdout.split()
            if host not in addrs:
                print(f"\n[WARNING] {host} is not an address on this machine ({' '.join(addrs) or 'none found'}).")
                print("          fast-discovery-server can only bind to a local address.")
                print("          On the robot this means the WiFi AP is not up yet.\n")
            cmd = ["fast-discovery-server", "-i", "0", "-l", host, "-p", port or "11811"]

        elif action == "rqt_graph":
            cmd = ["ros2", "run", "rqt_graph", "rqt_graph"]

        elif action == "tf2_tree":
            cmd = ["ros2", "run", "rqt_tf_tree", "rqt_tf_tree"]

        elif action == "mcap_record":
            cmd = [
                "ros2", "bag", "record",
                "-a",
                "-s", "mcap",
                "-o", os.path.abspath(run_name)
            ]
        elif action == "mcap_replay_rosbag":
            cmd = [
                "ros2", "bag", "play",
                os.path.abspath(run_name)
            ]
        elif action == "mcap_replay_interactive":
            bridge_script = os.path.abspath(os.path.join("Mcap", "mcap_tool.py"))
            cmd = [
                sys_python,
                bridge_script,
                "--replay",
                os.path.abspath(run_name)
            ]

        # Check if we should auto-record this session
        record_proc = None
        reward_proc = None
        
        # Start Reward Estimator automatically for deployments
        if action in ["isaac_sim", "mujoco", "mujoco_twin", "real_deploy", "eval_mujoco"]:
            reward_script = os.path.abspath(os.path.join("Controller", "reward_estimator_node.py"))
            reward_cmd = [sys_python, reward_script]
            
            if abs_ckpt:
                ckpt_dir = os.path.dirname(abs_ckpt)
                config_path = os.path.join(ckpt_dir, "training_phases.yaml")
                if os.path.exists(config_path):
                    reward_cmd.extend(["--ros-args", "-p", f"config_path:={config_path}"])
                    
            print("[Launcher] Starting Background Reward Estimator Node...")
            reward_proc = subprocess.Popen(reward_cmd, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
            time.sleep(0.5)

        if record_session:
            record_dir = "Mcap/Recordings"
            try:
                with open(CONFIG_PATH, 'r') as f:
                    cfg_data = yaml.safe_load(f)
                    record_dir = cfg_data.get("logging", {}).get("record_dir", "Mcap/Recordings")
            except Exception:
                pass
            os.makedirs(record_dir, exist_ok=True)
            
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            mcap_filename = os.path.join(record_dir, f"run_{action}_{timestamp}")
            abs_mcap = os.path.abspath(mcap_filename)
            
            print(f"\n[Launcher] Auto-recording enabled. Saving to: {mcap_filename}")
            
            record_cmd = [
                "ros2", "bag", "record",
                "-a",
                "-s", "mcap",
                "-o", abs_mcap
            ]
            # Start recorder in background
            record_proc = subprocess.Popen(record_cmd, env=env)
            time.sleep(0.5)

        try:
            subprocess.run(cmd, env=env)
        except KeyboardInterrupt:
            pass
        finally:
            if reward_proc is not None:
                print("\n[Launcher] Stopping Background Reward Estimator Node...")
                reward_proc.terminate()
                try:
                    reward_proc.wait(timeout=2.0)
                except subprocess.TimeoutExpired:
                    reward_proc.kill()
                    
            if record_proc is not None:
                print("\n[Launcher] Stopping background MCAP recorder...")
                record_proc.terminate()
                try:
                    record_proc.wait(timeout=2.0)
                except subprocess.TimeoutExpired:
                    record_proc.kill()
                print("[Launcher] Background recorder terminated cleanly.")

if __name__ == "__main__":
    main()
