package com.quadruped.console.ssh

import com.jcraft.jsch.ChannelExec
import com.jcraft.jsch.ChannelShell
import com.jcraft.jsch.JSch
import com.jcraft.jsch.KeyPair
import com.jcraft.jsch.Session
import com.jcraft.jsch.SocketFactory
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.InputStream
import java.io.OutputStream

data class SshTarget(val host: String, val port: Int, val user: String)

/**
 * The app's SSH key and known hosts, kept in the app's private storage. The key is
 * ECDSA P-256: generated by the platform's JCE, which Android has everywhere.
 */
class SshKeys(private val dir: File) {
    val privateKey = File(dir, "id_ecdsa")
    val publicKey = File(dir, "id_ecdsa.pub")
    val knownHosts = File(dir, "known_hosts")

    fun ensure(comment: String = "quadruped-console") {
        if (privateKey.exists() && publicKey.exists()) return
        dir.mkdirs()
        val kp = KeyPair.genKeyPair(JSch(), KeyPair.ECDSA, 256)
        kp.writePrivateKey(privateKey.path)
        kp.writePublicKey(publicKey.path, comment)
        kp.dispose()
    }

    fun publicLine(): String {
        ensure()
        return publicKey.readText().trim()
    }
}

/** A shell on the robot through a PTY, plus one-off commands. Blocking: call off the main thread. */
class SshClient(private val keys: SshKeys) {
    private var session: Session? = null
    private var shell: ChannelShell? = null

    val connected get() = session?.isConnected == true && shell?.isClosed == false

    /** Password is only for the first login, before the app's key is installed. */
    fun connect(
        target: SshTarget,
        password: String?,
        timeoutMs: Int = 8000,
        socketFactory: SocketFactory? = null,
    ): Session {
        keys.ensure()
        val jsch = JSch()
        jsch.addIdentity(keys.privateKey.path)
        keys.knownHosts.parentFile?.mkdirs()
        keys.knownHosts.createNewFile()
        jsch.setKnownHosts(keys.knownHosts.path)
        val s = jsch.getSession(target.user, target.host, target.port)
        if (!password.isNullOrEmpty()) s.setPassword(password)
        socketFactory?.let { s.setSocketFactory(it) }
        // First contact trusts and remembers the host key; a changed key is refused.
        s.setConfig("StrictHostKeyChecking", "accept-new")
        s.setConfig("PreferredAuthentications", "publickey,keyboard-interactive,password")
        // Notices a dead Wi-Fi link within ~15 s instead of waiting on TCP.
        s.serverAliveInterval = 5000
        s.serverAliveCountMax = 3
        s.connect(timeoutMs)
        session = s
        return s
    }

    /** Opens the interactive shell; returns (from robot, to robot). */
    fun openShell(cols: Int, rows: Int): Pair<InputStream, OutputStream> {
        val s = session ?: error("not connected")
        val ch = s.openChannel("shell") as ChannelShell
        ch.setPtyType("xterm-256color", cols, rows, 0, 0)
        val input = ch.inputStream
        val output = ch.outputStream
        ch.connect(5000)
        shell = ch
        return input to output
    }

    fun resize(cols: Int, rows: Int, widthPx: Int, heightPx: Int) {
        shell?.setPtySize(cols, rows, widthPx, heightPx)
    }

    /** Runs one command, returns (exit status, combined output). */
    fun exec(command: String, timeoutMs: Long = 10000): Pair<Int, String> {
        val s = session ?: error("not connected")
        val ch = s.openChannel("exec") as ChannelExec
        ch.setCommand(command)
        val out = ByteArrayOutputStream()
        ch.outputStream = null
        ch.setErrStream(out, true)
        val input = ch.inputStream
        ch.connect(5000)
        val end = System.currentTimeMillis() + timeoutMs
        val buf = ByteArray(4096)
        while (System.currentTimeMillis() < end) {
            while (input.available() > 0) {
                val n = input.read(buf)
                if (n < 0) break
                out.write(buf, 0, n)
            }
            if (ch.isClosed && input.available() == 0) break
            Thread.sleep(50)
        }
        val status = ch.exitStatus
        ch.disconnect()
        return status to out.toString()
    }

    /** Appends the app's public key to the robot's authorized_keys, once. */
    fun installKey(): Pair<Int, String> = exec(installKeyCommand(keys.publicLine()))

    fun disconnect() {
        shell?.disconnect()
        session?.disconnect()
        shell = null
        session = null
    }
}

fun installKeyCommand(publicLine: String): String {
    val line = publicLine.replace("'", "")
    return "umask 077; mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && " +
        "(grep -qxF '$line' ~/.ssh/authorized_keys || echo '$line' >> ~/.ssh/authorized_keys) && echo installed"
}
