# Unitree Go2 Configuration
robot_type: "go2"

# Safety Limits
saturation_limit: 0.90  # 90% of physical capacity
action_scale: 0.25

# Joint Limits (Radians)
# Note: These are software-defined limits for the CommandProcessor
joint_limits:
  abduction:
    min: -1.04
    max: 1.04
  hip:
    min: -1.57 # Front default, Hip Back is -0.52 to 4.53
    max: 3.49
  knee:
    min: -2.72
    max: -0.83

# Network (Default internal IP for Go2)
robot_ip: "192.168.123.161"
local_ip: "192.168.123.10"
