# Set up ROS 2 networking for a hand-typed shell.  SOURCE it, do not run it:
#
#     source Tools/ros_env.sh
#
# launcher.py does this automatically for the processes it spawns; this is the
# same logic for interactive shells (ros2 topic echo/hz, ros2 node list, ...).
#
# Two problems it solves, both of which look like "no topics" or "echo prints
# nothing" rather than an error:
#
#  1. The robot's WiFi AP drops multicast, so DDS discovery never completes.
#     A FastDDS discovery server on the robot replaces it. Needs
#     `fast-discovery-server` running there (launcher option [D]).
#  2. Both machines are multi-homed. A participant advertises every address it
#     owns, the peer picks one that does not route, and data silently never
#     arrives even though discovery succeeded. Pinning FastDDS to the address
#     that actually reaches the robot fixes it.
#
# Everything is derived at runtime, so this works from any laptop with no edits.

_cfg="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/Configs/config.yaml"

_server=$(sed -n 's/^[[:space:]]*discovery_server:[[:space:]]*"\?\([^"#]*\)"\?.*/\1/p' "$_cfg" 2>/dev/null | tr -d ' ')
[ -z "$_server" ] && _server="10.42.0.1:11811"
_domain=$(sed -n 's/^[[:space:]]*ros_domain_id:[[:space:]]*\([0-9]*\).*/\1/p' "$_cfg" 2>/dev/null | head -1)
[ -z "$_domain" ] && _domain=42

export ROS_DOMAIN_ID="$_domain"

_host="${_server%%:*}"
_port="${_server##*:}"
# Which of our addresses routes to the robot? Empty if there is no route.
# connect() on a UDP socket sends nothing - it just resolves the source address
# the kernel would pick. Uses python3 because the container has no iproute2.
_local=$(python3 -c "
import socket
try:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.settimeout(0.2)
    s.connect(('$_host', int('$_port' or 11811)))
    print(s.getsockname()[0]); s.close()
except Exception:
    pass" 2>/dev/null)
[ -z "$_local" ] && _local=$(ip route get "$_host" 2>/dev/null | sed -n 's/.*src \([0-9.]*\).*/\1/p' | head -1)

if [ -n "$_local" ] && [ "${_local%.*}" = "${_host%.*}" ]; then
    # Same subnet as the server => we are on the robot's AP, use the server.
    export ROS_DISCOVERY_SERVER="$_server"
    export ROS_SUPER_CLIENT=TRUE

    _profile="/tmp/quadruped_fastdds_${_local//./_}.xml"
    cat > "$_profile" <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Tools/ros_env.sh. Restricts FastDDS to ${_local}. -->
<dds>
  <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>iface_udp</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>${_local}</address>
        </interfaceWhiteList>
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="iface_only" is_default_profile="true">
      <rtps>
        <userTransports><transport_id>iface_udp</transport_id></userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
EOF
    export FASTRTPS_DEFAULT_PROFILES_FILE="$_profile"
    echo "[ros_env] wireless: domain=$ROS_DOMAIN_ID server=$ROS_DISCOVERY_SERVER pinned=$_local"
else
    # Cable: multicast works on a wired switch, so use plain discovery. Clear any
    # leftovers from a previous wireless session - they would break it silently.
    unset ROS_DISCOVERY_SERVER ROS_SUPER_CLIENT
    case "$FASTRTPS_DEFAULT_PROFILES_FILE" in
        */quadruped_fastdds_*) unset FASTRTPS_DEFAULT_PROFILES_FILE ;;
    esac
    echo "[ros_env] cable: domain=$ROS_DOMAIN_ID (multicast discovery)"
fi

# The daemon is itself a participant and caches the previous discovery view, so
# it keeps answering from the old world until stopped.
ros2 daemon stop >/dev/null 2>&1

unset _cfg _server _domain _host _port _local _profile
